### PR TITLE
Add chdir argument to support Terraform 0.15+

### PR DESCRIPTION
**Pull request by jleopold28**
## Merge Checklist

* [x] Have you linked this Pull Request to an [Issue](https://github.com/manheim/terraform-pipeline/issues)?
* [x] Have you updated any relevant README files, to explain how this new feature works (with examples)?
* [x] Have you added relevant test cases for your change?
* [x] Do all tests and code style checks pass with `./gradlew check --info`?
* [x] Have you successfully run your change in a pipeline in a Jenkins instance?
* [x] Have you updated the [CHANGELOG](https://github.com/manheim/terraform-pipeline/blob/master/CHANGELOG.md)?

Resolves Issue https://github.com/manheim/terraform-pipeline/issues/379 and https://github.com/manheim/terraform-pipeline/issues/395

### CODE REVIEW

**Comment by kmanning** [comment]
Will this break versions prior to 0.15?  The library is designed to support multiple different versions of terraform simultaneously, and I'd like to preserve that if possible. 

That that end, TerraformPlugin and the TerraformPluginVersion were designed to encapsulate version-specific differences.  Could this be a means for implementing the `-chdir` flag for newer versions, while maintaining existing functionality for existing versions?

**Comment by jleopold28** [comment]
@kmanning this will break versions to 0.15 ONLY when using the TerraformDirectoryPlugin. I'm going to look at making this backwards compatible

**Comment by kmanning** [comment]
Good work, and nice catches on the PassPlanPlugin, and TerraformVersion dependencies.

This PR is starting to get a little big, and I'm seeing 3 logically separate pieces: 
1. TerraformVersion was missing a hook for TerraformInit
2. TerraformDirectoryPlugin can be used independently of PassPlanPlugin.  In terms of PRs, improving TerraformDirectoryPlugin would provide value for users that do not use PassPlanPlugin.
3. Update (and fix the naming conventions) for PassPlanPlugin.

That might help in terms of review.

=====

For the PassPlan change, I'll repost these on that specific PR (but I'll note them here so you know ahead of time):

1. if an Issue doesn't already exist, could you create one?  I'd like to ensure that the CHANGELOG relates all changes to a relevant Issue.  See: https://github.com/manheim/terraform-pipeline#how-to-contribute
2. Could the README be split into 2 examples?  The first example should be as-is - just the PassPlanPlugin.  Then your change could introduce a second example of how it can be used in conjunction with TerraformDirectory.  To the extent that is possible, I'd like the first example of every plugin to be the minimum code necessary to get value out of the plugin.  Every subsequent example should illustrate variations to show how to get more value out.
3. [PassPlanFilePluginTest.groovy](https://github.com/manheim/terraform-pipeline/pull/415/files#diff-47e76b1bbf42ddb9b775101f47b1223788776d0c78a74f43300f4875d656ece6)  The apply method doesn't actually care about whether or not a directory is specified.  Is the stash/unstash closures that care.  I think the tests might be more focused if they were written against those methods, rather than the `apply` method.

**Review by kmanning — APPROVED** [review]
Looks great - :shipit:

**Pull request merged**
